displayName=Permanent Death
author=diskflip
description=A plugin that makes each kill "permanent", hiding the npc after it is killed.
tags=mode,entity,hider,monsters,npcs,unique
plugins=com.permanentdeath.PermanentDeathPlugin