displayName=Permanent Death
author=diskflip
description=A plugin that makes each kill "permanent", hiding the npc after it is killed.
tags=ironman,restriction,hider,permanent,kills
plugins=com.permanentdeath.PermanentDeathPlugin